name: Build

on:
  push:
    branches:
      - main

jobs:
  security:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Add permissions
        run: |
          chmod +x gradlew

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run snyk
        uses: snyk/actions/gradle@master
        with:
          args: --all-projects --debug